name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  fluttertoast: ^8.2.2
  flutter:
    sdk: flutter
  graphview: ^1.2.0
  google_maps_flutter: ^2.2.0
  google_fonts: ^4.0.0
  geocoding: ^2.1.0
  url_launcher: ^6.1.11
  location: ^4.4.0
  http: ^0.13.3
  image: ^3.2.2
  logging: ^1.1.0
  logger: ^1.3.0
  sqflite: ^2.0.0
  path: any
  provider: ^6.0.5
  image_picker: ^0.8.7+5
  custom_marker: ^1.0.0
  xml: ^6.0.1
  intl: ^0.17.0
  table_calendar: ^3.0.8
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  autocomplete_textfield: ^2.0.1
  flutter_local_notifications: ^14.1.1
  google_api_headers: ^1.0.0
  mockito: ^5.4.0
  matcher: ^0.12.13
  firebase_messaging: ^14.6.4
  firebase_analytics: ^10.4.3
  flutter_svg: ^1.0.1
  onesignal_flutter: ^3.5.1
  google_sign_in: ^6.1.4
  flutter_paypal: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/title_image.jpg
    - lib/Logo.png
    - lib/userData/pic.png